POST https://gitlab-discord-message-convert.herokuapp.com/https%3A%2F%2Fdiscordapp.com%2Fapi%2Fwebhooks%2F566260106765795338%2FlSZTQ_1Ff1RHQw_bMKCSj2Oc2K0R1_B0hEq0IsXBsawcZmtvpCn3vlWZGimUTX1XcVM7%2Fslack
Content-Type: application/json

{"username":"","attachments":[{"text":"fsadfs","color":"#345"}],"fallback":"KKAME (kkame) \u003chttps://gitlab.com/kkame/boot/issues/7#note_170975279|commented on issue #7\u003e in \u003chttps://gitlab.com/kkame/boot|kkame/boot\u003e: *sdfsdf*","text":"KKAME (kkame) \u003chttps://gitlab.com/kkame/boot/issues/7#note_170975279|commented on issue #7\u003e in \u003chttps://gitlab.com/kkame/boot|kkame/boot\u003e: *sdfsdf*"}


###


GET https://gitlab-discord-message-convert.herokuapp.com/

###